frr version 7.5.1_git
frr defaults traditional
hostname router6
no ipv6 forwarding
!
interface eth1
 ip address 10.0.136.6/24
!
interface eth2
 ip address 10.0.146.6/24
!
interface eth3
 ip address 10.0.167.6/24
!
interface lo
 ip address 192.168.10.6/32
!
router rip
 network 10.0.167.0/24
 redistribute ospf
 redistribute connected
!
router ospf
 ospf router-id 192.168.10.6
 redistribute rip route-map EST_RM_via_ACL
 network 10.0.136.0/24 area 2
 network 10.0.146.0/24 area 2
 network 192.168.10.0/32 area 2
!
access-list TEST_ACL seq 5 permit 192.168.2.0 0.0.0.255
access-list TEST_ACL seq 10 permit 192.168.10.7
!
route-map EST_RM_via_ACL permit 1
 match ip address TEST_ACL
!
line vty
!
