frr version 7.5.1_git
frr defaults traditional
hostname router2
no ipv6 forwarding
!
interface eth1
 ip address 10.0.124.2/24
!
interface eth2
 ip address 10.0.112.2/24
!
interface eth3
 ip address 10.0.125.2/24
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 frr_deamon
!
interface lo
 ip address 192.168.10.2/32
!
router ospf
 ospf router-id 192.168.10.2
 network 10.0.112.0/24 area 0
 network 10.0.124.0/24 area 0
 network 10.0.125.0/24 area 1
 network 192.168.10.0/24 area 0
 area 1 authentication message-digest
 area 1 nssa 
 area 1 nssa no-summary
!
line vty
!
