frr version 7.5.1_git
frr defaults traditional
hostname router4
no ipv6 forwarding
!
interface eth1
 ip address 10.0.134.4/24
!
interface eth2
 ip address 10.0.124.4/24
!
interface eth3
 ip address 10.0.146.4/24
!
interface lo
 ip address 192.168.10.4/32
!
router ospf
 ospf router-id 192.168.10.4
 network 10.0.124.0/24 area 0
 network 10.0.134.0/24 area 2
 network 10.0.146.0/24 area 2
 network 192.168.10.0/32 area 0
!
line vty
!
